import Head from "next/head";

// @ts-ignore
import useUser from "host/useUser";

export default function Home() {
  const { user, error, isLoading } = useUser();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-16 min-h-screen bg-blue-700">
        <p>
          Hola{user?.name && ` ${user?.name}`}, soy la aplicación {process.env.NEXT_PUBLIC_APP_NAME}
          {" "} corriendo en{" "}
          {process.env.NODE_ENV === "development" ? "local" : "remoto"} desde una subpágina.
        </p>
      </main>
    </>
  );
}
